SUPABASE_URL = "https://ldinyaqmftujryfjvswx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaW55YXFtZnR1anJ5Zmp2c3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NjM2MTQsImV4cCI6MjA3ODMzOTYxNH0.iRerh7GmIQ3iA__V7GGoY5xHEDo9_mVkTRERIjrnfdU"
